'use client'
import { Quicksand } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { useEffect } from "react";
import { useDisableBounce } from "./useDisableBounce";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };


export default function RootLayout({ children }) {
  // useDisableBounce()
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} bg-gradient-to-t from-[#eeecfb] to-[#fce8e5] md:bg-black md:bg-none md:from-transparent md:to-transparent antialiased max-w-[576px] h-screen mx-auto
 `}  
      >
        {children}
        <ToastContainer position="bottom-center" closeButton={false}/>
      </body>
    </html>
  );
}
